def icyayi() :
    print("Wahisemo icyayi")
    print("1. Uburyo bwiza bwo guhinga icyayi")
    print("2. Ifumbire nziza wakoresha")
    print("3. Uburyo bwiza bwi gusarura")
    info = int(input("Shiramo amahitamo yawe: "))
    if (info == 1) :
        print("Icyayi uburyo bwiza bwo kuwuhingamo")
        print("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam imperdiet purus ac tincidunt laoreet. Duis purus velit, auctor sit amet pretium quis, maximus quis neque. Suspendisse tellus odio, posuere vitae commodo eu, molestie vel velit. Proin porttitor, augue a porttitor mollis, sapien mi laoreet purus, id congue metus lorem eget ipsum. Donec quis sodales nunc, at fringilla urna. Donec tristique, metus vitae malesuada tempor, nisi massa tincidunt odio, sed cursus turpis lectus sed eros. Etiam venenatis commodo lorem a pretium. Mauris nec tellus id massa interdum iaculis sit amet at justo. Duis magna tellus, blandit ut dui a, pulvinar condimentum lacus. Ut elementum elit vitae massa tincidunt, id posuere ipsum dignissim. Mauris sed ligula eu velit imperdiet sodales sed eu tellus. Duis consequat nibh nec mollis efficitur. Donec ut sollicitudin eros. Fusce eleifend enim id ante posuere, sed aliquam diam molestie. Etiam lacus orci, malesuada quis ipsum dignissim, laoreet fermentum ligula. ")
    elif (info == 2) :
        print("icyayi ifumbire nziza wakoresha")
        print("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam imperdiet purus ac tincidunt laoreet. Duis purus velit, auctor sit amet pretium quis, maximus quis neque. Suspendisse tellus odio, posuere vitae commodo eu, molestie vel velit. Proin porttitor, augue a porttitor mollis, sapien mi laoreet purus, id congue metus lorem eget ipsum. Donec quis sodales nunc, at fringilla urna. Donec tristique, metus vitae malesuada tempor, nisi massa tincidunt odio, sed cursus turpis lectus sed eros. Etiam venenatis commodo lorem a pretium. Mauris nec tellus id massa interdum iaculis sit amet at justo. Duis magna tellus, blandit ut dui a, pulvinar condimentum lacus. Ut elementum elit vitae massa tincidunt, id posuere ipsum dignissim. Mauris sed ligula eu velit imperdiet sodales sed eu tellus. Duis consequat nibh nec mollis efficitur. Donec ut sollicitudin eros. Fusce eleifend enim id ante posuere, sed aliquam diam molestie. Etiam lacus orci, malesuada quis ipsum dignissim, laoreet fermentum ligula. ")
    elif (info == 2) :
        print("Icyayi uburyo bwiza bwo kuwusarura")
        print("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam imperdiet purus ac tincidunt laoreet. Duis purus velit, auctor sit amet pretium quis, maximus quis neque. Suspendisse tellus odio, posuere vitae commodo eu, molestie vel velit. Proin porttitor, augue a porttitor mollis, sapien mi laoreet purus, id congue metus lorem eget ipsum. Donec quis sodales nunc, at fringilla urna. Donec tristique, metus vitae malesuada tempor, nisi massa tincidunt odio, sed cursus turpis lectus sed eros. Etiam venenatis commodo lorem a pretium. Mauris nec tellus id massa interdum iaculis sit amet at justo. Duis magna tellus, blandit ut dui a, pulvinar condimentum lacus. Ut elementum elit vitae massa tincidunt, id posuere ipsum dignissim. Mauris sed ligula eu velit imperdiet sodales sed eu tellus. Duis consequat nibh nec mollis efficitur. Donec ut sollicitudin eros. Fusce eleifend enim id ante posuere, sed aliquam diam molestie. Etiam lacus orci, malesuada quis ipsum dignissim, laoreet fermentum ligula. ")
    