def rice() :
    print("You selected Rice")
    print("1. Best Farming Practices")
    print("2. Best Fertilizers & Insecticides")
    print("3. Best Harversting & Storing practices")
    info = int(input("Enter the choice of info you need: "))
    if (info == 1) :
        print("Rice best farming practices")
        print("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam imperdiet purus ac tincidunt laoreet. Duis purus velit, auctor sit amet pretium quis, maximus quis neque. Suspendisse tellus odio, posuere vitae commodo eu, molestie vel velit. Proin porttitor, augue a porttitor mollis, sapien mi laoreet purus, id congue metus lorem eget ipsum. Donec quis sodales nunc, at fringilla urna. Donec tristique, metus vitae malesuada tempor, nisi massa tincidunt odio, sed cursus turpis lectus sed eros. Etiam venenatis commodo lorem a pretium. Mauris nec tellus id massa interdum iaculis sit amet at justo. Duis magna tellus, blandit ut dui a, pulvinar condimentum lacus. Ut elementum elit vitae massa tincidunt, id posuere ipsum dignissim. Mauris sed ligula eu velit imperdiet sodales sed eu tellus. Duis consequat nibh nec mollis efficitur. Donec ut sollicitudin eros. Fusce eleifend enim id ante posuere, sed aliquam diam molestie. Etiam lacus orci, malesuada quis ipsum dignissim, laoreet fermentum ligula. ")
    elif (info == 2) :
        print("Rice best fertilizers & insecticides")
        print("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam imperdiet purus ac tincidunt laoreet. Duis purus velit, auctor sit amet pretium quis, maximus quis neque. Suspendisse tellus odio, posuere vitae commodo eu, molestie vel velit. Proin porttitor, augue a porttitor mollis, sapien mi laoreet purus, id congue metus lorem eget ipsum. Donec quis sodales nunc, at fringilla urna. Donec tristique, metus vitae malesuada tempor, nisi massa tincidunt odio, sed cursus turpis lectus sed eros. Etiam venenatis commodo lorem a pretium. Mauris nec tellus id massa interdum iaculis sit amet at justo. Duis magna tellus, blandit ut dui a, pulvinar condimentum lacus. Ut elementum elit vitae massa tincidunt, id posuere ipsum dignissim. Mauris sed ligula eu velit imperdiet sodales sed eu tellus. Duis consequat nibh nec mollis efficitur. Donec ut sollicitudin eros. Fusce eleifend enim id ante posuere, sed aliquam diam molestie. Etiam lacus orci, malesuada quis ipsum dignissim, laoreet fermentum ligula. ")
    elif (info == 2) :
        print("Rice best Harversting & Storing practices")
        print("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam imperdiet purus ac tincidunt laoreet. Duis purus velit, auctor sit amet pretium quis, maximus quis neque. Suspendisse tellus odio, posuere vitae commodo eu, molestie vel velit. Proin porttitor, augue a porttitor mollis, sapien mi laoreet purus, id congue metus lorem eget ipsum. Donec quis sodales nunc, at fringilla urna. Donec tristique, metus vitae malesuada tempor, nisi massa tincidunt odio, sed cursus turpis lectus sed eros. Etiam venenatis commodo lorem a pretium. Mauris nec tellus id massa interdum iaculis sit amet at justo. Duis magna tellus, blandit ut dui a, pulvinar condimentum lacus. Ut elementum elit vitae massa tincidunt, id posuere ipsum dignissim. Mauris sed ligula eu velit imperdiet sodales sed eu tellus. Duis consequat nibh nec mollis efficitur. Donec ut sollicitudin eros. Fusce eleifend enim id ante posuere, sed aliquam diam molestie. Etiam lacus orci, malesuada quis ipsum dignissim, laoreet fermentum ligula. ")
    